# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-18 06:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelineevent',
            name='background',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='timelineevent',
            name='display_date',
            field=models.CharField(max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='timelineevent',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='timelineevent',
            name='group',
            field=models.CharField(max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='timelineevent',
            name='media',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='timelineevent',
            name='media_caption',
            field=models.CharField(max_length=140, null=True),
        ),
        migrations.AlterField(
            model_name='timelineevent',
            name='media_credit',
            field=models.CharField(max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='timelineevent',
            name='media_thumbnail',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='timelineevent',
            name='slide_type',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='timelineevent',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='timelineevent',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
