# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-18 06:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0003_auto_20161218_0608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelineevent',
            name='background',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='timelineevent',
            name='group',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='timelineevent',
            name='media',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timelineevent',
            name='media_caption',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
        migrations.AlterField(
            model_name='timelineevent',
            name='media_credit',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='timelineevent',
            name='media_thumbnail',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timelineevent',
            name='slide_type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='timelineevent',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
