# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-28 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0004_auto_20161218_0609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelineevent',
            name='display_date',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
    ]
