# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 04:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0005_auto_20161228_1629'),
    ]

    operations = [
        migrations.CreateModel(
            name='Background',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=7, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='timelineevent',
            name='background_id',
            field=models.IntegerField(null=True),
        ),
    ]
