# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 05:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0006_auto_20161229_0437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelineevent',
            name='background_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
