# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 05:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0008_remove_timelineevent_background'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timelineevent',
            name='background_id',
        ),
        migrations.AddField(
            model_name='timelineevent',
            name='background',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='timeline.Background'),
        ),
    ]
